-- 의료기관 정보 테이블 생성
CREATE TABLE IF NOT EXISTS `im_medical_institutions` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `encrypted_code` VARCHAR(500) NOT NULL UNIQUE COMMENT '암호화요양기호',
    `institution_name` VARCHAR(200) NOT NULL COMMENT '요양기관명',
    `category_code` VARCHAR(10) COMMENT '종별코드',
    `category_name` VARCHAR(50) COMMENT '종별코드명',
    `sido_code` VARCHAR(10) COMMENT '시도코드',
    `sido_name` VARCHAR(50) COMMENT '시도코드명',
    `sigungu_code` VARCHAR(10) COMMENT '시군구코드',
    `sigungu_name` VARCHAR(50) COMMENT '시군구코드명',
    `eupmyeondong` VARCHAR(100) COMMENT '읍면동',
    `postal_code` VARCHAR(10) COMMENT '우편번호',
    `address` TEXT COMMENT '주소',
    `phone_number` VARCHAR(20) COMMENT '전화번호',
    `homepage_url` VARCHAR(500) COMMENT '병원홈페이지',
    `establishment_date` DATE COMMENT '개설일자',
    `total_doctors` INT DEFAULT 0 COMMENT '총의사수',
    `general_medicine_doctors` INT DEFAULT 0 COMMENT '의과일반의 인원수',
    `medicine_intern_doctors` INT DEFAULT 0 COMMENT '의과인턴 인원수',
    `medicine_resident_doctors` INT DEFAULT 0 COMMENT '의과레지던트 인원수',
    `medicine_specialist_doctors` INT DEFAULT 0 COMMENT '의과전문의 인원수',
    `dental_general_doctors` INT DEFAULT 0 COMMENT '치과일반의 인원수',
    `dental_intern_doctors` INT DEFAULT 0 COMMENT '치과인턴 인원수',
    `dental_resident_doctors` INT DEFAULT 0 COMMENT '치과레지던트 인원수',
    `dental_specialist_doctors` INT DEFAULT 0 COMMENT '치과전문의 인원수',
    `oriental_general_doctors` INT DEFAULT 0 COMMENT '한방일반의 인원수',
    `oriental_intern_doctors` INT DEFAULT 0 COMMENT '한방인턴 인원수',
    `oriental_resident_doctors` INT DEFAULT 0 COMMENT '한방레지던트 인원수',
    `oriental_specialist_doctors` INT DEFAULT 0 COMMENT '한방전문의 인원수',
    `midwives` INT DEFAULT 0 COMMENT '조산사 인원수',
    `location_x` DECIMAL(15,10) COMMENT '좌표(X) - 경도',
    `location_y` DECIMAL(15,10) COMMENT '좌표(Y) - 위도',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    
    INDEX `idx_encrypted_code` (`encrypted_code`),
    INDEX `idx_institution_name` (`institution_name`),
    INDEX `idx_sido_sigungu` (`sido_code`, `sigungu_code`),
    INDEX `idx_category` (`category_code`),
    INDEX `idx_location` (`location_x`, `location_y`),
    INDEX `idx_establishment_date` (`establishment_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='의료기관 정보'; 