version: '3.8'
services:
    ubuntu:
        container_name: parmderi_nginx_php81
        build:
            context: ./images/ubuntu
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./source:/var/www/html
            - ./images/ubuntu/conf/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
            - "443:443"
    db:
        image: mariadb:latest
        container_name: parmderi_mariadb
        restart: always
        environment:
            MYSQL_DATABASE: htest
            MYSQL_USER: devh
            MYSQL_PASSWORD: A77ila@
            MYSQL_ROOT_PASSWORD: A77ila@7612
        volumes:
            - ./mariadb_data:/var/lib/mysql    
        ports:
            - "3306:3306"